version: '3.8'
services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: eq-frontend-prod
    ports:
      - "8084:8084"
    environment:
      - NODE_ENV=production
