version: '3.8'

services:
  frontend-dev:
    build: 
      context: .
      dockerfile: ./Dockers/dev/Dockerfile
    container_name: eq-frontend-dev
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    network_mode: "host"
