version: '3.8'

services:
  frontend-staging:
    build:
      context: .
      dockerfile: ./Dockers/staging/Dockerfile
    container_name: eq-frontend-staging
    ports:
      - "8083:8082"
    environment:
      - NODE_ENV=staging
