version: '3.8'
services:
  backend-staging:
    build:
      context: .
      dockerfile: ./Dockers/staging/Dockerfile
    container_name: eq-backend-staging
    ports:
      - "4002:4000"
    environment:
      - NODE_ENV=staging
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - PORT=4000
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
    env_file:
      - .env
    restart: unless-stopped
