on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: edumosaic-backend

    steps:


      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Pull and Deploy Backend
        working-directory: /var/www/projects/eq-aditya-j-mern-stack-internship-2025/backend/
        run: |
          echo "Pulling latest code for backend" 
        
          git fetch --all &&
          git pull origin main &&
          npm install &&
          pm2 restart edumosaic-backend
