on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: [self-hosted, edumosaic-backend]  

    steps:

      - name: Set up SSH key for GitHub Actions
        run: |
          if [ ! -d "$HOME/.ssh" ]; then mkdir -p ~/.ssh; fi
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa-Adi
          chown -R $USER:$USER ~/.ssh
          chmod 600 ~/.ssh/id_rsa-Adi
          chmod 700 ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa-Adi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'

      - name: Pull and Deploy Backend
        working-directory: /var/www/projects/eq-aditya-j-mern-stack-internship-2025/backend/
        run: |
          echo "Pulling latest code for backend" 
        
          
          git pull 
          npm install &&
          pm2 restart index.js --name "edumosaic-backend"
