name: Build

on:
  push:
    branches:
      - main


jobs:
  sonar:
    runs-on: self-hosted  # This makes GitHub Actions run on your Ubuntu machine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=http://192.168.0.104:9080 \
            -Dsonar.login=$SONAR_TOKEN

