name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: corona_tracker
    permissions: 
        contents: read
        id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Run SonarScanner with Debug
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-project \
            -Dsonar.sources=src \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -X  # Enables full debug mode
