name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: corona_tracker
    permissions: 
        contents: read
        id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Run SonarScanner with Debug
        run: |
          sonar-scanner -Dsonar.projectKey=corona_tracker \
              -Dsonar.sources=src \
              -Dsonar.host.url=http://192.168.0.104:9000 \
              -Dsonar.login=squ_e9eff9fcc2a7a7977040b6b75011929e50e68003 \
              -X
