name: Frontend SonarQube Scan

on:
  repository_dispatch:
    types: [run-sonarqube]

jobs:
  analyze-frontend:
    name: SonarQube Frontend Scan
    runs-on: sonar

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend (again)
        run: |
          cd frontend
          npm run build

      - name: Run SonarQube Scanner
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=frontend-app \
            -Dsonar.sources=frontend/src \
            -Dsonar.host.url=http://192.168.0.104:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
