name: MERN Stack Code Quality Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better SonarQube analysis
      
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: '.'
          args: >
            -Dsonar.organization=your-org
            -Dsonar.projectKey=your-mern-app
            -Dsonar.sources=frontend/src,backend/src
            -Dsonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
